import {Musician} from './types/musician';
export {BIO_DATA};
import interiewdemo from '../assets/video/interviews/demo-interview.mp4';

const BIO_DATA: Array<Musician> = [
  {
    name: "Adrienne Brown",
    instrument: "Viola",
    whichSymphony: "COS",
    bioText: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    name: "Ali Bylund",
    instrument: "Clarinet",
    whichSymphony: "COS",
  },
  {
    name: "Alice Long",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Amy Anderson",
    instrument: "French Horn",
    whichSymphony: "COS",
    bioText: "Et netus et malesuada fames.",
  },
  {
    name: "Amy Wheeler",
    instrument: "Cello",
    whichSymphony: "COS",
  },
  {
    name: "Barry Crenshaw",
    instrument: "Tuba",
    whichSymphony: "COS",
    bioText: "Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet.",
  },
  {
    name: "Ben Kroeker",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "Bethany Willis",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Bill Ortman",
    instrument: "Percussion",
    whichSymphony: "COS",
  },
  {
    name: "Bill Weaver",
    instrument: "Bass",
    whichSymphony: "COS",
  },
  {
    name: "Carolyn Rouse",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Carrie Howell",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "Carson Perl",
    instrument: "Bass",
    whichSymphony: "COS",
  },
  {
    name: "Cheri Redgrave",
    instrument: "Percussion",
    whichSymphony: "COS",
  },
  {
    name: "Craig Olson",
    instrument: "Trumpet",
    whichSymphony: "COS",
  },
  {
    name: "Dara Robertson",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "Dennis Senff",
    instrument: "Timpani",
    whichSymphony: "COS",
  },
  {
    name: "Eleanor Davidson",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Elly Jocham",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Emma Smith",
    instrument: "Cello",
    whichSymphony: "COS",
  },
  {
    name: "Erik Hoagland",
    instrument: "Bass Trombone",
    whichSymphony: "COS",
  },
  {
    name: "Gae Thwing",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Gayle Hoagland",
    instrument: "Bass Clarinet",
    whichSymphony: "COS",
  },
  {
    name: "Hannah Ortman",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Jamie Gregory",
    instrument: "Bassoon",
    whichSymphony: "COS",
  },
  {
    name: "Jean Shrader",
    instrument: "Piano",
    whichSymphony: "COS",
  },
  {
    name: "Jeff Stormont",
    instrument: "Oboe",
    whichSymphony: "COS",
  },
  {
    name: "Jenny Marsden",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "John Fawcett",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Johnny Downs",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Jonathan Moore",
    instrument: "French Horn",
    whichSymphony: "COS",
  },
  {
    name: "Josh Parr",
    instrument: "Trumpet",
    whichSymphony: "COS",
  },
  {
    name: "Karina Klaver",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "Kathy Gault",
    instrument: "Piano",
    whichSymphony: "COS",
  },
  {
    name: "Ken Steiger",
    instrument: "Trumpet",
    whichSymphony: "COS",
  },
  {
    name: "Larry Meyers",
    instrument: "Percussion",
    whichSymphony: "COS",
  },
  {
    name: "Laura Leighton",
    instrument: "Harp",
    whichSymphony: "COS",
  },
  {
    name: "Leah Naftalin",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Lenore Gilbert",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Leo Reincke",
    instrument: "Cello",
    whichSymphony: "COS",
  },
  {
    name: "Leslie Knight",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "Levi Miller",
    instrument: "Bass",
    whichSymphony: "COS",
  },
  {
    name: "Lia Keener",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Liliana Newman",
    instrument: "Violin",
    whichSymphony: "COS",
    bioText: "Morbi quis commodo odio aenean sed.",
  },
  {
    name: "Lynn Lakin",
    instrument: "Piccolo",
    whichSymphony: "COS",
  },
  {
    name: "Maggie McHugh",
    instrument: "Viola",
    whichSymphony: "COS",
  },
  {
    name: "Mateo Garza",
    instrument: "Violin",
    bioText: "Cras fermentum odio eu feugiat pretium nibh ipsum consequat nisl.",
    whichSymphony: "COS",
  },
  {
    name: "Melissa Frantz",
    instrument: "Violin",
    whichSymphony: "COS",
    bioText: "Nunc non blandit massa enim nec dui nunc mattis enim.",
  },
  {
    name: "Reid Kajikawa",
    instrument: "Bassoon",
    whichSymphony: "COS",
  },
  {
    name: "Robert Gregory",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Ronald DeLano",
    instrument: "Bass",
    whichSymphony: "COS",
  },
  {
    name: "Ronald DeLano",
    instrument: "Bass",
    whichSymphony: "COS",
  },
  {
    name: "Sam Taylor",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Sarah Kilroy",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Sarah Ruzicka",
    instrument: "Violin",
    whichSymphony: "COS",
    bioText: "In fermentum et sollicitudin ac orci phasellus egestas tellus rutrum.",
  },
  {
    name: "Sean Van Hatten",
    instrument: "Bassoon",
    whichSymphony: "COS",
    bioText: "Dui ut ornare lectus sit amet est.",
  },
  {
    name: "Skylar Grayson",
    instrument: "Percussion",
    whichSymphony: "COS",
  },
  {
    name: "Sophia Wilkins",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Sue Steiger",
    instrument: "Flute",
    whichSymphony: "COS",
  },
  {
    name: "Terri Grimm",
    instrument: "Violin",
    whichSymphony: "COS",
  },
  {
    name: "Tina Filsinger",
    instrument: "Cello",
    whichSymphony: "COS",
  },
  {
    name: "Travis Allen",
    instrument: "Cello",
    whichSymphony: "COS",
    bioText: "Mi tempus imperdiet nulla malesuada pellentesque.",
  },
  {
    name: "Wendy Bloom",
    instrument: "Bassoon",
    whichSymphony: "COS",
    bioText: "At urna condimentum mattis pellentesque id nibh tortor id aliquet.",
  },
  {
    name: "Amy Mitchell",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Andreas Lang",
    instrument: "French Horn",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Aria Hartley",
    instrument: "Violin",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Brenda Simmons",
    instrument: "Violin",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Chris Thomas",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "David Morris",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Denise Graves",
    instrument: "Violin",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Eddy Robinson",
    instrument: "Bass",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Elizabeth Thorpe",
    instrument: "Violin",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Emma Chaput",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Evan Sigvaldsen",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Gayle Hoagland",
    instrument: "Clarinet",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Jake Ortman",
    instrument: "Percussion",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Janet Gesme",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Jeff Briggs",
    instrument: "Trumpet",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Jeff Stormont",
    instrument: "English Horn",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Joshua Evans",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Julian Simmons",
    instrument: "Cello",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Kristin Guy",
    instrument: "Oboe",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Lisa Pofelski-Rosa",
    instrument: "Bass",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Lynn Lakin",
    instrument: "Flute",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Michelle Kajikawa",
    instrument: "French Horn",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Nicole Stavale",
    instrument: "Violin",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Sam Conklin",
    instrument: "Violin",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Stefanie Janin-Brohamer",
    instrument: "Flute",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Tim Lynch",
    instrument: "French Horn",
    whichSymphony: "COS",
    video: interiewdemo,
  },
  {
    name: "Wendy Bloom",
    instrument: "Oboe",
    whichSymphony: "COS",
    video: interiewdemo,
    bioText: "Vel turpis nunc eget lorem dolor sed.",
  },
  {
    name: "Zeta Gesme",
    instrument: "Cello"  ,
    whichSymphony: "COS",
    video: interiewdemo,
  },
];
